// Note on React and Redux:
// Redux is used to construct the application state, React provides the views to display that state
// The two libraries are inherently disconnected and its only through the use of 'react-redux' library that we are able to connect the two
// Our application state is generated by reducer functions (see index.js inside ./reducers/)

import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore, applyMiddleware } from 'redux';

import App from './components/app';
import reducers from './reducers';

const createStoreWithMiddleware = applyMiddleware()(createStore);

ReactDOM.render(
  <Provider store={createStoreWithMiddleware(reducers)}>
    <App />
  </Provider>
  , document.querySelector('.container'));
